### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by gazdela12** [matth-x/ArduinoOcpp#13]
Hello, I try to upload occp on ESP32 but it can't even build. 
Here is screenshot, could you please help me?
![image](https://user-images.githubusercontent.com/90112775/132106773-81e87f00-54a1-4983-9b12-271563260efd.png)

**Comment by 204maker** [comment]
I completely agree. 
I am having errors building the code in Visual Studio Code on PlatformIO.
May I ask what version release is working at the moment?
How about a more detailed instruction on setting the environment for a successful build in Visual Studio Code on PlatformIO?

**Comment by matth-x** [comment]
The error message means that the linker doesn't find the compiled versions of the `loop()` and `setup()` function. Somehow the compiler doesn't compile them. Have you copied the example files into the source folder of your project?

I use PIO core version `5.1.1`.

**Comment by gazdela12** [comment]
I managed to fix it but now I got this:
![image](https://user-images.githubusercontent.com/90112775/135750734-2a29d8fc-542e-4129-a85a-54652236786a.png)

**Comment by HackLink123** [comment]
Hi gazdela12  I met the same problem as you.How did you solve it?

**Comment by matth-x** [comment]
@gazdela12 The issue here was that `echo.websocket.org` is down unfortunately. I've updated the URL in the example sketch.

**Comment by Navjot0005** [comment]
Hi @matth-x 
I am facing the exact same problem.
How I can troubleshoot this??
Do I need to make a new project ??
Because I did not make.
What I am currently doing unzip the downloaded folder and without any change opening in PlatformIO.
I did not make new project.
Can you guide me how shall I start this because I am not very good familiar with PlatformIO. ?
Shall I made new project in PlatformIO?
if I made new then how I add MicroOcPP in the new project?
Any help will be appreciated.
Waiting for reply..
