### ISSUE TITLE
Tier-2 Connectors Support 

### ISSUE THREAD

**Issue by HARSHAL93** [matth-x/ArduinoOcpp#15]
Appreciated your efforts to provide great platform.
 As I have implemented single connector (1-Tier ) EV Charger with steve server and found working as expected. 
As steve is supporting multiple connector I am trying add another connector with same charge point in ESP32 but not having idea to where to start modifying the existing code, it will be very helpful if I get some support to add another connector support in existing code.

**Comment by matth-x** [comment]
Hi Harshal,

Great to hear that! You can understand the `ArduinoOcpp.h` as a facade module of the library, i.e. it simplifies the access to all functions. Due to that simplification, it doesn't promote the support for mulitple connectors.

Instead of relying on the facade module, you can work directly with the modules. Please take `ArduinoOcpp.cpp` as a starting point and increase `OCPP_NUMCONNECTORS` by one so you get three logical connectors. The ID of the first connector is 1, the second is 2 and to address the charge point as a whole, use connector ID 0. In every place where `ArduinoOcpp.cpp` uses `OCPP_ID_OF_CONNECTOR`, you have to decide wheter to address connector 1 or 2.
