### ISSUE TITLE
Is ArduinoOcpp is complaint with "White paper: Improved security for OCPP 1.6-J" ?

### ISSUE THREAD

**Issue by Bhuvi-Naveen** [matth-x/ArduinoOcpp#158]
Dear @matth-x ,

I wanted to check if the ArduinoOcpp supports features based on "White paper Improved security for OCPP 1.6-J". Can you please confirm.

Regards,
Bhuvi-Naveen

**Comment by matth-x** [comment]
Hi @Bhuvi-Naveen, no, ArduinoOcpp doesn't provide an implementation of the Security Whitepaper messages. It is up to the EVSE vendor to implement these. The reason is that in my current projects, the TLS certificates are either part of the firmware binaries (which is legit for IoT controllers) or the communication controllers don't encrypt the traffic themselves but rely on external hardware for that. If you can imagine to make a support request for that feature, please don't hesitate to reach out.

Also refer to the [ArduinoOcpp docs](https://matth-x.github.io/ArduinoOcpp/security/#ocpp-security-whitepaper-and-iso-15118) for a recent statement on this.
