### ISSUE TITLE
A question for transaction-related message handling

### ISSUE THREAD

**Issue by zhushengsheng001** [matth-x/ArduinoOcpp#162]
Hi Matth-x:
I notice that in  OCPP-1.6.pdf page 26,
It says:
It is therefore allowed to send, for example, an Authorize request or a
Notifications request before the transaction-related message queue has been emptied, so that
customers are not kept waiting and urgent notifications are not delayed

Could you tell how this feature implemented? Thanks!

**Comment by matth-x** [comment]
Hi @zhushengsheng001, the order of the message queue is immutable in the ArduinoOcpp implementation. The reason is that this simplifies the messaging mechanism a lot and reduces the risk of errors.

Anyway I believe that this rule is more relevant to the SOAP-version of OCPP and has no huge impact with typical WebSocket communication patterns. If some measurements show the opposite, I would be very curious to learn about it though.
