### ISSUE TITLE
Multiple connectors example

### ISSUE THREAD

**Issue by fanzypantz** [matth-x/ArduinoOcpp#25]
Hi, I see there is a commit for multiple connectors support and that the example was changed, but that was for the single connector from the looks of it, could be I'm blind. 

How would you implement multiple connectors with this library?

**Comment by matth-x** [comment]
Hi, the core of the library supports multiple connectors. I haven't added it to `ArduinoOcpp.h` yet, because I'm still not 100% sure if it belongs there or if I should make an extra `ArduinoOcppMulti.h`, sorry.

In the meantime, you can implement multiple connectors by not relying on `ArduinoOcpp.h` which is just a facade module anyway, but by accessing the internals of the library directly. To do so, please copy the functions `startTransaction()`, `authorize()`, ect., from `ArduinoOcpp.cpp` into your project and adapt `OCPP_NUMCONNECTORS` and `OCPP_ID_OF_CONNECTOR` according to your needs. Hope this helps.
