### ISSUE TITLE
Always getting false/Low for ocppPermitsCharge() with SECC example

### ISSUE THREAD

**Issue by whuizdis** [matth-x/ArduinoOcpp#64]
To begin with, I'm using the example code in SECC and communication is working and I could establish OCPP comms and send bootnotifications and Heartbeat signals. But, for some reason I am getting OCPPpermitsCharge() as FALSE and because of which I cannot do startTransaction(). Is there anything Im missing?

**Comment by matth-x** [comment]
Hi, `ocppPermitsCharge()` specifies if the EVSE is allowed to finally turn on the PWM generator and close the contactors. It is the result of a successful transaction rather than a prerequisite of it.

The actual prerequisites of starting a transaction are `isAvailable()` and if the user is authorized to charge. You can find out the latter by sending an `authorize(...)` request and looking it up in the response.

If you have a follow-up question, feel free to reopen.
